-- Add RESUBSCRIBED to events type enum column
ALTER TABLE `events` MODIFY COLUMN `type` ENUM('SENT', 'DELIVERED', 'OPENED', 'CLICKED', 'REPLIED', 'BOUNCED', 'UNSUBSCRIBED', 'RESUBSCRIBED', 'FAILED') NOT NULL DEFAULT 'SENT';
